# Generated by Django 2.0.7 on 2018-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=100)),
                ('CarModel', models.CharField(max_length=10)),
                ('CarClass', models.CharField(choices=[('F', 'Pierwsza'), ('ECO', 'Ekonomiczna'), ('B', 'Biznesowa'), ('S', 'Specjalna')], max_length=10)),
                ('CarType', models.CharField(choices=[('S', 'Sedan'), ('LI', 'Limousine'), ('S_LI', 'Stretch Limousine'), ('MB', 'MiniBus'), ('SUV', 'Suv'), ('VAN', 'Van')], max_length=10)),
                ('CarInfo', models.TextField()),
                ('CarID', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
